### ISSUE TITLE
讓開源再次偉大 (邁向版本 1.0 之路)

### ISSUE THREAD

**Issue by Yukaii** [Yukaii/vscode-ptt#9]
## 工程部

- [ ] eslint
- [x] PR/Issue template
- [ ] Basic Test Architecture
- ~~fork ptt-client 並規劃 roadmap~~ 免了
- [ ] 各式 badge
	- vsc ext badge
	- travis badge
- [ ] GitHub action tag 自動 publish 到 marketplace
- [ ] VSCode react tree view

## 設計部

- [ ] 一個還可以的 Logo
	- 結合 VSCode 和 PTT。嗯，果如其名。
- ~~UX Revisit~~ 算了，每次 revisit 都不了了之(?
- 更新 README，現在實在太醜

## 一人社群自嗨法

- [ ] SNS Account
	- Or open source community chat like Spectrum/Matrix
- [ ] Product Roadmap (抄 VSCodeVim)
- [x] 拆 milestone
- [x] Contribution Guide
- [ ] General Documentation
- [ ] Architectural Documentation (現在基本上就是沒有)
- GitHub moderation
	- Issue/Milestone Rules
	- GitHub flow: default branching
	- Release schedule

**Comment by Yukaii** [comment]
幹還是都用中文好了，PTT 都台灣人再用用什麼英文辣

**Comment by caasi** [comment]
用 eslint 吧～ https://github.com/typescript-eslint/tslint-to-eslint-config

**Comment by 34292885** [comment]
請問有幫vscode-ptt上色的辦法嗎，目前比較容易看清回覆文章的是設成Batch，但仍然不理想

**Comment by Yukaii** [comment]
因為 agent 時代來臨，所以希望能重啟維護和功能開發 :p
